### ISSUE TITLE
how can i use this library.

### ISSUE THREAD

**Issue by billgo** [MiteshSharma/StorageService#1]
how can i use this library.

**Comment by MiteshSharma** [comment]
1. This is not a library but a service which runs in a stand alone way and talks to other services using APIs. Receive api request and perform storage related operations like upload file on some server.
2. Currently it only helps upload content on S3, but if you want you can use this code and extend for any other cloud provider. Already implemented it keeping this in mind.
3. We assume that everywhere there is a bucket (or container or single folder) and files, so if you have created bucket(or create one using API provided) then you can upload any file using this service.
4. This is not a battle tested code as i made it for my personal project and not used extensively. so you might need to understand code a bit so if you need to do any changes you can do it, or may be i can help by doing it for you.
5. I used GoDep for all dependency management, so you can download all needed libraries to make it run locally.

Let me know if i can help you with running this on your local or production machine.

**Comment by billgo** [comment]
Can you write a demo for me. Now i just want to learn how to use you project, I want store something in localhost. But i don't know how to create bucket. 
I call the api but alway response "Error creating bucket with given name.
thanks  man.

**Comment by MiteshSharma** [comment]
1. Hope you have added all aws related key and secret in config file.
2. Hope you know that bucket name should be unique accross aws region and other restriction: http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html. Do try some unique name and check if this works, best is to add dametime in bucket name for testing as that will be unique for sure.
3. Do check for this error log and see what comes after it "Error on creating bucket ....", here .... should give you real reason.

If all this is already satisfied then let me know, will check once on my end.

**Comment by billgo** [comment]
if I change the ProviderType to "File", then I need to configure S3 information or not ?
Because i don't have S3 account.  so i can't use.
thanks.

**Comment by MiteshSharma** [comment]
Provider Type is "File" for FileSystem with base file path (RootPath) and "AWS" for S3. 
1. What are you using for testing File or AWS?
2. If you are not able to create file in provider type File, then do check for permission to create file in that folder. This should work fine.
3. In File provider, no S3 information is needed.

Let me know more details regarding issue, so i can debug it further.

**Comment by billgo** [comment]
`"ProviderType": "File",`
`"RootPath": "/StorageService/upload"`
 S3Config is empty.

I just `go get github.com/MiteshSharma/StorageService ` then `go run main.go`.

I want to save some pictures in localhost, and different kinds of pictures save in different bucket. 
I think you project can do somethings like this.

**Comment by MiteshSharma** [comment]
yes, this configuration is correct. Just make sure you have "/StorageService/upload" directory structure created on you local machine, if this is mac or ubuntu or for windows create a folder and update this path. 
This is base path where all you files and folders are created, so you can change it to whatever path you need to use. 
Once this is done, then you can make API calls with pictures to save them in specified folder .
structure.

Are you still getting same issue, after updating your RootPath with needed path?

"FileStorage": {
      "RootPath": "/StorageService/upload" <--- Room path, must exist on your computer or update this with some other folder path which exists. 
    }

**Comment by billgo** [comment]
`"RootPath": "/Users/Billgo/Gowork/src/github.com/MiteshSharma/StorageService/upload"`
Then i use the function send the request.
`curl -H "Content-Type: application/json" -d '{"name":"sample"}' localhost:8080/bucket/sample`
correct or not.

**Comment by MiteshSharma** [comment]
RootPath can be anything, even this is fine.

Reading from bucketName params. Need to work on documentation :) 
Try this :  curl -H "Content-Type: application/json" -d '{"bucketName":"sample"}' localhost:8080/bucket/sample

**Comment by billgo** [comment]
```
MiteshSharma curl -H "Content-Type: application/json" -d '{"bucketName":"sample"}' localhost:8080/bucket/sample
"Error creating bucket with given name."%
```

The same problem.

**Comment by MiteshSharma** [comment]
@billgo 
Tried exact scenario and it is working fine on my setup with ProviderType as "File". 
Are you also getting other error messages like "Error creating directory" or any other error message as only this is not of much help. Seems like some small configuration or folder permission issue.

**Comment by MiteshSharma** [comment]
@billgo Does it works or are we good here?

**Comment by billgo** [comment]
@MiteshSharma upload to S3 is fine, but i can't upload to local machine. thanks man, i will review you code , then solve this problem. if finish i send the PR to you.

**Comment by MiteshSharma** [comment]
@billgo Thanks man. That's great to hear. Please send PR, that will help community to use it further. Hope i was of help. :)
